services:
  lasa-dev:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./config/:/etc/lasad/
    depends_on:
      - redis
    dns:
      # required, otherwise DNS server misbehaving
      - 8.8.8.8
      - 8.8.4.4
    profiles: [dev]
  lasa:
    image: atcr.io/anhgelus.world/lasa
    volumes:
      - ./config/:/etc/lasad/
    depends_on:
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4
    profiles: [prod]
  redis:
    image: docker.io/library/redis:alpine
