services:
  lasa:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./config.toml:/etc/lasad.toml
    depends_on:
      - redis
    dns:
      # required, otherwise DNS server misbehaving
      - 8.8.8.8
      - 8.8.4.4
  redis:
    image: docker.io/library/redis:alpine
