domain = "example.org"
port = 8000
#legal_notice_url = "https://example.org/legal"
# if you want to log HTTP 404 responses
#log_not_found = true
# if you want to log HTTP 400 responses
#log_bad_request = true

# if you are using redis
#[cache]
#host = "localhost"
#port = 6379
#db = 0
#duration = 60 # cache duration in minutes

# if redis requires auth
#[cache.auth]
#username = ""
#password = ""
#client_name = ""
